version: 0.2

phases:
  install:
    commands:
      - cinst nodejs.install
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: cognito-practice